name: Test run

on:
  pull_request:
  schedule:
    - cron: 0 6 * * 5
  workflow_dispatch:

jobs:
  errorformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7.2.0

      - run: uv sync
      - run: uv run blinter-simple-output samples/batchfiles/good/good.cmd samples/batchfiles/bad/bad.bat
